---
title: "Lab 00 - Hello IDS!"
author: "Remi Bain"
date: "`r Sys.Date()`"
output: html_document
---

### Load packages and data

```{r load-packages, message=FALSE}
library(tidyverse) 
```

### Exercises 16-17

We set up the data frame. Edit the data below to include information about your team members.

```{r setup-tibble}
team_data <- tibble(
  name = c("Remi", "Justus", "Cyrus", 
           "Ivy", "member 4"),
  github_username = c("remibn", "justusedinburgh2026-web", "Cyrus1764", 
                      "4weiZhang", "username 4"), 
  colour = c("yellow", "yellow", "blue", 
             "Blue", "colour 4"),
  hobby = c("Maths", "Basketball", "Maths", 
            "Computer Games", "hobby 4"),
  favourite_number = c(1, 7, 1, 4, NA)
  )

team_data
```

### Exercise 18

We now work on visualising our data. 

```{r bar-plot}
p1 <- ggplot(data = team_data, 
             mapping = aes(x = github_username, 
                           y = favourite_number,
                           fill = colour), 
             ) +
   geom_col() +
   scale_fill_identity()
p1
```

Shows favourite_number against github_username, with the colour of each bar matching the corresponding favourite colour.